variables: variables.yml

### Templates

templates:
  anchors:
    _trakt_credentials: &trakt_credentials
      username: mmosquera91
      account: mmosquera91@gmail.com

    _movie_lookup: &movie_lookup
      metainfo_movie: yes
      imdb_lookup: yes
      tmdb_lookup: yes

    _tv_lookup: &tv_lookup
      thetvdb_lookup: yes
      trakt_lookup:
        <<: *trakt_credentials

  trakt_tv_list: &trakt_tv_list
    trakt_list:
      <<: *trakt_credentials
      list: '{? trakt.tv_list ?}'
      type: shows
